### PR TITLE
send email with local sendmail rather than SMTP

### LINKED ISSUE #5: Consider supporting local sendmail rather than SMTP for email
Thanks for taking on a modernisation of this tool!

I looked into using it, but I'm not too excited about duplicating my SMTP credentials in both the TrueNAS config and the YAML config for autobackup. It would probably not be a particularly big change to your code to take the formatted message and pipe it into a `/usr/sbin/sendmail` subprocess (somewhat like how the original version just pipes to `mail`). Have you considered that? Would you be open to a patch?

### PR DESCRIPTION
**Pull request by 0xabu**
Fixes #5 

I recognise this is probably not exactly what you want, sorry. Feel free to adapt as you wish.

### CODE REVIEW

**Comment by ghan1t** [comment]
Thanks for the quick PR. So my mistake was calling mail instead of sendmail?
I will have a look at it later. I would like to preserve the SMTP and offer both options.

**Comment by 0xabu** [comment]
BTW I only tested running this as `admin` and not yet `root` but I'd be surprised if that changes things. In my tests I was using the python venv.

**Comment by 0xabu** [comment]
> BTW I only tested running this as `admin` and not yet `root` but I'd be surprised if that changes things. In my tests I was using the python venv.

This was a lie, but I didn't realise it at the time.

In my testing, I was using `venv/bin/python3` explicitly, but I had not run the `activate` script which changes your PATH. The latter does break sendmail, because TrueNAS sendmail is a script that uses python. If PATH has been modified by the venv, it finds the wrong (venv) python. The workaround I implemented here is to reset the PATH for the subprocess, but really if you're not using any other subprocesses that need the venv, it might be better *not* to source `activate` in `trigger.sh` and instead to invoke the correct python interpreter from the venv -- i.e. `${VENV}/bin/python3 monitor.py`.

**Comment by ghan1t** [comment]
@0xabu have you tested your branch on your TrueNAS machine to run a backup?
Does monitor.py not need the modified PATH to get the installed dependencies? I once had the problem that after an OS update the venv was somehow broken and it could not find the dependencies installed in the venv unless I either set `export PYTHONPATH="${VENV}/lib/python3.11/site-packages` or recreated the venv. That's why I wonder if simply calling the correct python interpreter is enough?

**Comment by 0xabu** [comment]
I just tested this (on top of the other changes in this PR) and it worked fine for me doing a backup and sending email:

```
diff --git a/mail_util.py b/mail_util.py
index 9d42562..6a2621c 100644
--- a/mail_util.py
+++ b/mail_util.py
@@ -16,8 +16,8 @@ def send_email(subject, body, config: EmailConfig, logger: Logging):

     # On TrueNAS, sendmail is a python script, so we must not leak our private venv to it.
     child_env = os.environ
-    if 'VIRTUAL_ENV' in os.environ:
-        child_env['PATH'] = '/usr/local/bin:/usr/bin:/bin:/usr/games'
+    #if 'VIRTUAL_ENV' in os.environ:
+    #    child_env['PATH'] = '/usr/local/bin:/usr/bin:/bin:/usr/games'

     # Send the email
     try:
diff --git a/trigger.sh b/trigger.sh
index d41d6e9..b1a7f2b 100755
--- a/trigger.sh
+++ b/trigger.sh
@@ -191,12 +191,12 @@ start_application() {
         exit
     fi
     # Activate the virtual environment
-    echo "Activating python venv in ${VENV}"
-    . "${VENV}/bin/activate"
+    #echo "Activating python venv in ${VENV}"
+    #. "${VENV}/bin/activate"

     # Start monitoring udev events
     echo "Spawn monitor.py in the background..."
-    (cd "${SCRIPT_DIR}" && python3 monitor.py $CONFIG_PATH &)
+    (cd "${SCRIPT_DIR}" && "${VENV}/bin/python3" monitor.py $CONFIG_PATH &)
     # python3 monitor.py $CONFIG_PATH
 }
```

**Comment by ghan1t** [comment]
I'm pulling this into a branch, as I want to modify it to allow the smtp mail as an option and warn users of the config change. Thanks for your efforts @0xabu. I'll close the issue once I merged it into main.

**Comment by 0xabu** [comment]
Ok, sure, beware that I made a couple of fixes after the version in this PR:
https://github.com/0xabu/trigger-zfs-autobackup/blob/main/trigger.py#L141-L145

The main change is explicitly setting `email.policy.default` (which is in fact not the default in all Python versions) and setting `cte='8bit'`. Together these fix an issue with the TrueNAS sendmail not correctly handling the default quoted-printable email encoding and mangling lone lines in the messages.

**Comment by ghan1t** [comment]
@0xabu A couple of changes is a bit modest ;-) Looks like you reworked it a lot and it shows that you know much more what you're doing than what I cobbled together 😁. I'll try your script and then probably merge it into my main as is.
Can we keep one repo, in a way that others know where to find the latest and greatest version?

**Comment by 0xabu** [comment]
By "a couple of changes" I just meant the email-related part that was highlighted.

About the rest -- I probably got a bit carried away, but I was doing it partly to understand the code and mostly to address my own taste and needs. I don't expect you to merge it as-is let alone look at it if you don't want to. I even threw out some of your features (git-based installer, SMTP email, logging to file, word-splitting of args).

Of course it's open source (now officially so, thanks), so you're free to use any of the code, but I don't feel like another fork would be particularly harmful.

**Pull request merged**
